# Generated by Django 4.2.14 on 2024-07-25 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MonitorTypes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitortypes",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="创建日期"
            ),
        ),
        migrations.AlterField(
            model_name="monitortypes",
            name="modified_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="修改时间"
            ),
        ),
    ]
