# Generated by Django 4.2.14 on 2024-08-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MonitorTypes", "0003_resume"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resume",
            options={"verbose_name": "信息", "verbose_name_plural": "用户个人信息"},
        ),
    ]
