# Generated by Django 4.2.14 on 2024-08-11 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interview", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="candidate",
            options={
                "permissions": [
                    ("export", "Can export candidate list"),
                    ("notify", "notify interviewer for candidate review"),
                ],
                "verbose_name": "一些信息",
                "verbose_name_plural": "一些信息",
            },
        ),
        migrations.AlterField(
            model_name="candidate",
            name="first_interviewer_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="first_interviewer_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="待选项",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="first_result",
            field=models.CharField(
                blank=True,
                choices=[("建议复试", "建议复试"), ("待定", "待定"), ("放弃", "放弃")],
                max_length=256,
                verbose_name="手势结果",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="first_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="1-5分，极优秀: >=4.5，优秀: 4-4.4，良好: 3.5-3.9，一般: 3-3.4，较差: <3分",
                max_digits=2,
                null=True,
                verbose_name="手势",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="hr_interviewer_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hr_interviewer_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="待选项",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="hr_result",
            field=models.CharField(
                blank=True,
                choices=[("建议录用", "建议录用"), ("待定", "待定"), ("放弃", "放弃")],
                max_length=256,
                verbose_name="声音结果",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="hr_score",
            field=models.CharField(
                blank=True,
                choices=[("S", "S"), ("A", "A"), ("B", "B"), ("C", "C")],
                max_length=10,
                verbose_name="声音",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="second_interviewer_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="second_interviewer_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="待选项",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="second_result",
            field=models.CharField(
                blank=True,
                choices=[("建议录用", "建议录用"), ("待定", "待定"), ("放弃", "放弃")],
                max_length=256,
                verbose_name="温度结果",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="second_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="1-5分，极优秀: >=4.5，优秀: 4-4.4，良好: 3.5-3.9，一般: 3-3.4，较差: <3分",
                max_digits=2,
                null=True,
                verbose_name="温度",
            ),
        ),
    ]
