# Generated by Django 4.2.14 on 2024-08-12 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interview", "0002_alter_candidate_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="first_interviewer_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="first_interviewer_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="处理人",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="hr_interviewer_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hr_interviewer_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="处理人",
            ),
        ),
        migrations.AlterField(
            model_name="candidate",
            name="second_interviewer_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="second_interviewer_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="处理人",
            ),
        ),
    ]
