# Generated by Django 4.2.14 on 2024-08-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0005_alter_candidate_first_result"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="hand_picture",
            field=models.ImageField(
                blank=True, upload_to="hand_images/", verbose_name="手势结果"
            ),
        ),
    ]
